data:
  source: "data/es_futures.parquet"
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  symbols: ["ES"]
  bar_size: "1min"

strategy:
  class_name: "BollingerStrategy"
  module_path: "strategies.bollinger"
  params:
    lookback: 20
    z_score: 2.0
    position_size: 0.1
  initial_capital: 100000.0

execution:
  slippage_bps: 1.0
  commission_bps: 0.5
  min_tick_size: 0.25
  max_spread_bps: 5.0
  fill_delay_ms: 0

risk:
  max_position_size: 100
  max_drawdown: 0.15
  stop_loss_bps: 200
  position_limit_pct: 0.1

reporting:
  output_dir: "./results/bollinger_es"
  save_equity_curve: true
  save_fills: true
  save_risk_metrics: true
  generate_html_report: true
  plot_style: "plotly"

metadata:
  strategy_type: "mean_reversion"
  asset_class: "futures"
  description: "Bollinger Bands strategy on ES futures"
