# Fundamental Strategies Configuration
# Category A: 1-100

data:
  source: "data/fundamentals.parquet"
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  symbols:
    [
      "AAPL",
      "MSFT",
      "GOOGL",
      "AMZN",
      "TSLA",
      "META",
      "NVDA",
      "NFLX",
      "ADBE",
      "CRM",
    ]
  bar_size: "1D"

# Price-to-Book Deep Value Strategy
price_to_book_deep_value:
  strategy:
    class_name: "PriceToBookDeepValue"
    module_path: "strategies.fundamental_strategies"
    params:
      rebalance_frequency: "monthly"
      universe_size: 1000
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/price_to_book_deep_value"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# EV/EBITDA Cheapness Spread Strategy
ev_ebitda_cheapness:
  strategy:
    class_name: "EVEBITDACheapnessSpread"
    module_path: "strategies.fundamental_strategies"
    params:
      rebalance_frequency: "monthly"
      universe_size: 1000
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/ev_ebitda_cheapness"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# Magic Formula Strategy
magic_formula:
  strategy:
    class_name: "MagicFormula"
    module_path: "strategies.fundamental_strategies"
    params:
      rebalance_frequency: "monthly"
      universe_size: 1000
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/magic_formula"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# Quality-Value Combo Strategy
quality_value_combo:
  strategy:
    class_name: "QualityValueCombo"
    module_path: "strategies.fundamental_strategies"
    params:
      rebalance_frequency: "monthly"
      universe_size: 1000
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/quality_value_combo"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# Shareholder Yield Strategy
shareholder_yield:
  strategy:
    class_name: "ShareholderYield"
    module_path: "strategies.fundamental_strategies"
    params:
      rebalance_frequency: "monthly"
      universe_size: 1000
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/shareholder_yield"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true
