# Momentum and Technical Strategies Configuration
# Categories D & E: 161-340

data:
  source: "data/price_data.parquet"
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  symbols:
    [
      "AAPL",
      "MSFT",
      "GOOGL",
      "AMZN",
      "TSLA",
      "META",
      "NVDA",
      "NFLX",
      "ADBE",
      "CRM",
    ]
  bar_size: "1D"

# Cross-Sectional Momentum Strategy
cross_sectional_momentum:
  strategy:
    class_name: "CrossSectionalMomentum"
    module_path: "strategies.momentum_strategies"
    params:
      lookback_period: 252
      momentum_period: 252
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/cross_sectional_momentum"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# Time-Series Momentum Strategy
time_series_momentum:
  strategy:
    class_name: "TimeSeriesMomentum"
    module_path: "strategies.momentum_strategies"
    params:
      lookback_period: 252
      momentum_period: 126
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/time_series_momentum"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# Moving Average Crossover Strategy
moving_average_crossover:
  strategy:
    class_name: "MovingAverageCrossover"
    module_path: "strategies.momentum_strategies"
    params:
      lookback_period: 252
      momentum_period: 50
      fast_period: 20
      slow_period: 50
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/moving_average_crossover"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# RSI Momentum Strategy
rsi_momentum:
  strategy:
    class_name: "RSIMomentum"
    module_path: "strategies.momentum_strategies"
    params:
      lookback_period: 252
      momentum_period: 14
      rsi_period: 14
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/rsi_momentum"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# MACD Momentum Strategy
macd_momentum:
  strategy:
    class_name: "MACDMomentum"
    module_path: "strategies.momentum_strategies"
    params:
      lookback_period: 252
      momentum_period: 26
      fast_period: 12
      slow_period: 26
      signal_period: 9
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/macd_momentum"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# Bollinger Bands Momentum Strategy
bollinger_bands_momentum:
  strategy:
    class_name: "BollingerBandsMomentum"
    module_path: "strategies.momentum_strategies"
    params:
      lookback_period: 252
      momentum_period: 20
      bb_period: 20
      bb_std: 2.0
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/bollinger_bands_momentum"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# RSI Signal Strategy
rsi_signal:
  strategy:
    class_name: "RSISignalStrategy"
    module_path: "strategies.momentum_strategies"
    params:
      rsi_period: 14
      oversold: 30
      overbought: 70
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/rsi_signal"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true

# MACD Signal Strategy
macd_signal:
  strategy:
    class_name: "MACDSignalStrategy"
    module_path: "strategies.momentum_strategies"
    params:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    initial_capital: 100000.0

  execution:
    slippage_bps: 1.0
    commission_bps: 0.5
    min_tick_size: 0.01

  risk:
    max_position_size: 100
    max_drawdown: 0.15
    position_limit_pct: 0.1

  reporting:
    output_dir: "./results/macd_signal"
    save_equity_curve: true
    save_fills: true
    save_risk_metrics: true
    generate_html_report: true
